// fetch-transit.js — refresh the transit-visa nationality lists from
// Wikipedia's "Airport transit visa" article, so data/transit-visa-data.js
// stays current without hand-editing.
//
// We extract two regimes:
//   - Schengen Airport Transit Visa (Annex IV common list)
//   - UK Direct Airside Transit Visa (DATV "visa national" list)
//
// Strategy: pull the article's section wikitext via the MediaWiki API, find
// the country links in the relevant section, map names → ISO2 via iso-map.json.
// SAFETY: if a list comes back implausibly short, we keep the previous value
// from the existing data file. The output is therefore always complete.
//
// Run:
//   node fetch-transit.js            (writes ../data/transit-visa-data.js)
//   node fetch-transit.js --dry-run  (print, don't write)
//
// Wired into .github/workflows/daily-refresh.yml.

const fs = require("fs");
const path = require("path");
const fetch = require("node-fetch");

const OUT_PATH = path.join(__dirname, "..", "data", "transit-visa-data.js");
const ISO_MAP = JSON.parse(fs.readFileSync(path.join(__dirname, "iso-map.json"), "utf-8"));
const UA = "AtlasVisaGlobe/1.0 (https://travelnow.info; transit-refresh)";
const DRY_RUN = process.argv.includes("--dry-run");

// Minimum plausible sizes — below these we treat the scrape as failed and
// fall back to the previous list rather than shipping a broken map.
const MIN_SCHENGEN = 8;
const MIN_GB = 20;

// A few Wikipedia name variants the iso-map doesn't carry verbatim.
const NAME_ALIASES = {
  "Democratic Republic of the Congo": "CD",
  "DR Congo": "CD",
  "Republic of the Congo": "CG",
  "Ivory Coast": "CI",
  "Côte d'Ivoire": "CI",
  "North Korea": "KP",
  "South Korea": "KR",
  "Myanmar": "MM",
  "Burma": "MM",
  "Palestine": "PS",
  "State of Palestine": "PS",
  "Syrian Arab Republic": "SY",
  "Moldova": "MD",
  "Russia": "RU",
  "Russian Federation": "RU",
  "Eswatini": "SZ",
  "Cape Verde": "CV",
  "East Timor": "TL",
  "Timor-Leste": "TL",
};

function nameToIso(name) {
  const n = name.trim();
  if (ISO_MAP[n]) return ISO_MAP[n];
  if (NAME_ALIASES[n]) return NAME_ALIASES[n];
  // Try stripping parentheticals / footnote markers.
  const cleaned = n.replace(/\s*\([^)]*\)\s*/g, "").replace(/\[[^\]]*\]/g, "").trim();
  if (ISO_MAP[cleaned]) return ISO_MAP[cleaned];
  if (NAME_ALIASES[cleaned]) return NAME_ALIASES[cleaned];
  return null;
}

// Pull the parsed wikitext of a section by fetching the whole article in
// wikitext and slicing between section headings.
async function fetchArticleWikitext(title) {
  const url = "https://en.wikipedia.org/w/api.php"
    + "?action=parse&prop=wikitext&format=json&formatversion=2"
    + "&page=" + encodeURIComponent(title);
  const r = await fetch(url, { headers: { "User-Agent": UA } });
  if (!r.ok) throw new Error(`HTTP ${r.status} for ${title}`);
  const j = await r.json();
  return j?.parse?.wikitext || "";
}

// Given wikitext and a heading regex, return the chunk until the next heading.
function sectionChunk(wikitext, headingRe) {
  const lines = wikitext.split("\n");
  let inSection = false, out = [];
  for (const line of lines) {
    const isHeading = /^==[^=].*==\s*$/.test(line) || /^===[^=].*===\s*$/.test(line);
    if (inSection && isHeading) break;
    if (inSection) out.push(line);
    if (!inSection && headingRe.test(line)) inSection = true;
  }
  return out.join("\n");
}

// Extract [[Country]] / [[Country|label]] wikilinks → ISO2 set.
function isoSetFromChunk(chunk) {
  const set = new Set();
  const re = /\[\[([^\]|#]+)(?:\|[^\]]*)?\]\]/g;
  let m;
  while ((m = re.exec(chunk)) !== null) {
    const iso = nameToIso(m[1]);
    if (iso) set.add(iso);
  }
  return [...set];
}

function readPrevious() {
  try {
    const text = fs.readFileSync(OUT_PATH, "utf-8");
    const window = {};
    new Function("window", text)(window);
    return window.TRANSIT_REQUIRED_OVERRIDES || {};
  } catch (e) { return {}; }
}

function serialize(data) {
  return [
    "// AUTO-GENERATED by backend/fetch-transit.js (daily cron) — do not edit by hand.",
    "// Schengen Airport Transit Visa (Annex IV) + UK Direct Airside Transit Visa lists.",
    "// transit-visa-rules.js applies these over its built-in defaults at load.",
    "",
    "window.TRANSIT_REQUIRED_OVERRIDES = " + JSON.stringify(data, null, 2) + ";",
    "",
  ].join("\n");
}

(async () => {
  const prev = readPrevious();
  const out = {
    lastUpdated: new Date().toISOString().slice(0, 10),
    SCHENGEN: prev.SCHENGEN || [],
    GB: prev.GB || [],
  };

  try {
    const wt = await fetchArticleWikitext("Airport transit visa");

    const schChunk = sectionChunk(wt, /(Schengen|Annex IV)/i);
    const schList = isoSetFromChunk(schChunk);
    if (schList.length >= MIN_SCHENGEN) {
      out.SCHENGEN = schList.sort();
      console.log(`Schengen ATV: ${schList.length} nationalities`);
    } else {
      console.warn(`Schengen scrape too short (${schList.length}) — keeping previous ${out.SCHENGEN.length}`);
    }

    const gbChunk = sectionChunk(wt, /(United Kingdom|Direct Airside Transit|DATV)/i);
    const gbList = isoSetFromChunk(gbChunk);
    if (gbList.length >= MIN_GB) {
      out.GB = gbList.sort();
      console.log(`UK DATV: ${gbList.length} nationalities`);
    } else {
      console.warn(`UK scrape too short (${gbList.length}) — keeping previous ${out.GB.length}`);
    }
  } catch (e) {
    console.warn(`Transit scrape failed (${e.message}) — keeping previous lists`);
  }

  const text = serialize(out);
  if (DRY_RUN) { console.log(text); return; }
  fs.writeFileSync(OUT_PATH, text);
  console.log(`Wrote ${OUT_PATH}`);
})().catch(e => { console.error(e); process.exit(1); });
