// Turkish text for /about/ — see scripts/tr-strings/index.js for the format.
module.exports = {
  // <h2> Who's behind this
  "99b4a858": `Bu sitenin arkasında kim var`,
  "7359edb3": `travelnow.info, <strong>Uygar Atalay</strong> tarafından geliştirilen ve sürdürülen bağımsız bir projedir. Basit bir bıkkınlıktan doğdu: bir seyahat planladığımda kimin nereye vize gerektirdiğini bulmak, dağınık devlet sayfalarını ve güncelliğini yitirmiş forum yazılarını karıştırmak demekti. Soruyu dürüstçe yanıtlayan tek bir harita istedim, o yüzden onu yaptım ve çalışır durumda tutuyorum. Bir şirket değil, tek kişilik bir proje; gelen her mesajı okuyorum.`,
  "179b5bbe": `travelnow.info, tanınan her pasaportu kapsayan, güvenilir ve düzenli güncellenen kamuya açık kaynaklardan vize politikası bilgilerini derler. Zamanlanmış bir görev tüm veri setini her 24 saatte bir yeniden oluşturur; dolayısıyla gördüğün harita, kaydettiğimiz son değişikliklerin en fazla bir gün gerisindedir. Otomatik verinin üzerine, makinelerin yanıldığı durumlar için elle hazırlanmış bir düzeltme katmanı tutuyoruz: bölgeler, serbest dolaşım alanları, oturma izni yükseltmeleri ve giriş yasakları. Her biri yayımlanmadan önce resmî bir kaynakla kontrol edilir. Yan paneldeki “Son değişiklikler” akışı bir önceki günün farklarını gösterir.`,
  "300ee5c1": `Tek katı kuralımız var: <strong>vize verisi uydurmayız.</strong> Bir bilgi kaynaklandırılamıyorsa tahmin yürütmek yerine dışarıda bırakırız. Bir ülke sayfasında yanlış görünen bir şey varsa pasaportu, varış noktasını ve mümkünse bir kaynak bağlantısını yazarak <a href="mailto:hello@travelnow.info">bana e-posta at</a>. Düzeltmeler önceliklidir ve genellikle aynı hafta içinde yayına girer.`,
  "ef7d0a73": `Site sana zaman kazandırdıysa ya da yanlış bir rezervasyonu önlediyse, <a href="https://buymeacoffee.com/travelnowinfo" target="_blank" rel="noopener">bana bir kahve ısmarlayabilirsin</a>: tamamen isteğe bağlı, site her durumda ücretsiz kalıyor.`,
  "cfc2ab16": `Geri bildirim, veri düzeltmesi veya iş birliği talepleri için <a href="mailto:hello@travelnow.info">hello@travelnow.info</a> adresine yaz. Ayrıntılar için <a href="/contact/">iletişim sayfasına</a> bak. <a href="https://github.com/Uygara/atlas-visa-globe/issues" rel="noopener">GitHub</a>'da konu (issue) da açabilirsin.`,
  "de7c9ba2": `Ülke bayrakları Unicode emoji'dir. Bu sitedeki diğer tüm içerik olduğu gibi, bilgi amaçlı sunulur; rezervasyondan önce her vize gerekliliğini varış ülkesinin büyükelçiliğiyle doğrula. <a href="/terms/">Kullanım Koşulları</a> ve <a href="/privacy/">Gizlilik Politikası</a> sayfalarımıza bak.`,
};
