// Turkish text for /guides/transit-visa-guide/ — see scripts/tr-strings/index.js.
// "Airside"/"landside" stay in English: they are the terms travellers meet at the airport.
module.exports = {
  "6ab3780f": `<a href="/">travelnow.info</a> › <a href="/guides/">Rehberler</a> › Transit vizeler`,
  "f07861e0": `Ülkeyi ziyaret bile etmiyorsun — sadece iki saatliğine uçak değiştiriyorsun. Elbette buna hiçbir şey gerekmez, değil mi? Çoğu aktarma için bu doğrudur. Ancak bir dizi ülke, havaalanından hiç çıkmasan bile bir <strong>transit vizesi</strong> ister ve yakalanmak, kalkış şehrinde uçağa alınmamak demektir. İşte aktarmanın bunlardan biri olup olmadığını nasıl anlayacağın.`,
  "6ab85e82": `Airside ve landside: can alıcı ayrım`,
  "81a66abe": `İki tür transit vardır ve kuralları tamamen farklıdır.`,
  "c6a2fde5": `<strong>Airside (uluslararası) transit</strong> — güvenli uluslararası bölgenin içinde kalırsın, göçmenlik kontrolünden geçmezsin ve doğrudan bir sonraki uçuşuna bağlanırsın. Birçok ülke buna serbestçe izin verir.`,
  "4b69df1a": `<strong>Landside transit</strong> — göçmenlik kontrolünden geçip yeniden check-in yapman gerekir; örneğin havaalanı değiştirdiğin, bagajını alıp yeniden teslim ettiğin ya da bagajların son varış noktasına kadar etiketlenmediği için. Göçmenlik hattını geçtiğin an hukuken “giriş” yapmış olursun; bu yüzden o ülkenin istediği her türlü giriş iznine ihtiyacın olur.`,
  "e3159453": `<strong>Sorulacak ilk soru:</strong> bagajlarım son varış noktasına kadar mı kaydedilecek ve uluslararası bölgede mi kalacağım? Evetse airside'sındır. Bagajları almak, havaalanı değiştirmek ya da güvenli alandan çıkmak zorundaysan landside'sındır — ve varış noktasının normal giriş kuralları geçerlidir.`,
  "16b58dd1": `İnsanları şaşırtan havaalanları`,
  "848411d6": `Salt airside transitte bile bazı ülkeler belirli uyruklardan özel bir transit vizesi ister:`,
  "2d10cbb3": `<strong>Schengen Bölgesi</strong>, Bölge'ye girmeden aktarma yapılsa bile belirli bir uyruk listesi için Havaalanı Transit Vizesi (ATV) uygular.`,
  "a701f8a0": `<strong>Birleşik Krallık</strong>, birçok uyruk için Doğrudan Airside Transit Vizesi (DATV) şartı uygular ve liste bariz değildir — yolcular sıklıkla muaf olmadıkları hâlde muaf olduklarını varsayar.`,
  "42f8e015": `<strong>Amerika Birleşik Devletleri</strong> en büyük örnektir: airside transit <em>yoktur</em>. Steril bir uluslararası bölge bulunmadığından, bir ABD havaalanından aktarma yapan her yolcu göçmenlik kontrolünden geçmek zorundadır ve bu yüzden vizesiz giriş (ESTA ile) ya da C-1 transit vizesi gerekir. ABD üzerinden aktarma, vize açısından bir giriştir.`,
  "74222201": `<strong>Kanada</strong>, uyruğa ve kullanılan transit programına göre aktarmalar için eTA ya da transit vizesi ister.`,
  "dbae99a9": `Transit zamanla sınırlı olduğunda`,
  "7d531bfc": `Bazı ülkeler kısa süreli vizesiz transite izin verir — örneğin havaalanından çıkıp şehri görmek için belirli sayıda saat ya da yalnızca devam uçuşun belirli bir süre içindeyse vizesiz airside transit. Bu “vizesiz transit” düzenlemeleri yararlıdır ama özeldir: çoğu zaman süre sınırı içinde onaylı bir devam bileti ister ve belirli uyrukları dışarıda bırakabilir. Süre sınırını ve koşulları katı kabul et.`,
  "5c7b15b8": `Kendi aktarmanı nasıl kontrol edersin`,
  "0bd5761c": `Yalnızca başlangıç ve bitiş değil, güzergâhının <em>dokunduğu</em> her ülkeyi belirle.`,
  "09bb6615": `Her biri için airside mı landside mı olacağına karar ver (bagaj son noktaya kadar kayıtlı mı? aynı havaalanı mı? uluslararası bölgede mi kalıyorsun?).`,
  "53079a55": `O havaalanında <em>senin uyruğun</em> için transit kuralını kontrol et — transit kuralları uyruğa özeldir.`,
  "6b1129a2": `Şüphedeysen havayoluna sor: doğru belgeye sahip değilsen seni uçağa almayacak olan onlardır; bu yüzden kapıda önemli olan onların cevabıdır.`,
  "ec34a9f6": `Havaalanından hiç çıkmazsam vize gerekir mi?`,
  "f099b8f1": `Bazen. Çoğu ülke serbest airside transite izin verir, ancak Schengen Bölgesi, Birleşik Krallık ve diğerleri belirli uyruklardan airside olsa bile transit vizesi ister — ABD'de ise hiç airside transit yoktur.`,
  "919e5043": `ABD'de aktarma gerçekten vize ya da ESTA gerektirir mi?`,
  "af6c96ec": `Evet. Uluslararası transit bölgesi bulunmadığı için bir ABD havaalanından aktarma yapmak ABD'ye girmek sayılır; bu yüzden onaylı bir ESTA ile vizesiz giriş ya da bir transit/ziyaretçi vizesi gerekir.`,
  "01dfe59d": `Aynı şehirde havaalanı değiştirirsem ne olur?`,
  "d4d3c78d": `Havaalanı değiştirmek neredeyse her zaman seni landside yapar — güvenli alandan çıkarsın ve ülkenin normal giriş kurallarını karşılaman gerekir.`,
  "06e03ee6": `Haritada gör`,
  "b108d4b4": `<a href="/transit-map/">Transit haritasını aç</a> — tüm dünya, uyruğun için airside transitin açık mı yoksa transit vizesinin gerekli mi olduğuna göre renklendirilmiş.`,
  "3bdbc512": `<a href="/esta-rules/">ESTA kontrolü</a> — Amerika Birleşik Devletleri üzerinden aktarma yapmak için bile gerekli.`,
  "6f2979b8": `<a href="/">Etkileşimli küre</a> — her ülke için tam vize durumu.`,
};
