// Turkish text for /guides/etias-2026-explained/ — see scripts/tr-strings/index.js.
module.exports = {
  "96d57131": `<a href="/">travelnow.info</a> › <a href="/guides/">Rehberler</a> › ETIAS 2026`,
  "f12c71a1": `2026'da ETIAS: kimler için gerekli ve vizeden farkı ne`,
  "34e4f7f9": `Yazan: Uygar Atalay · Güncelleme: 17 Haziran 2026 · yaklaşık 5 dakikalık okuma`,
  "c4ff2a15": `ETIAS, Avrupa Seyahat Bilgi ve İzin Sistemi'dir (European Travel Information and Authorisation System): birçok vizesiz ziyaretçinin Avrupa'nın büyük bölümüne girmeden önce yapması gereken yeni bir çevrimiçi kayıttır. Yıllardır konuşuluyor ve defalarca ertelendi; bu rehber onun ne olduğunu, kimleri etkilediğini ve önemli bir gerçeği açıklıyor: bir vize <strong>değildir</strong>.`,
  "07d5e243": `ETIAS nedir`,
  "3b5b85f2": `ETIAS, Schengen Bölgesi'ne zaten vizesiz girebilen kişiler için bir seyahat öncesi izindir. Bir büyükelçiliğe başvurmak yerine pasaport bilgilerin, geçmişe dair sorular ve seyahat planlarınla kısa bir çevrimiçi form doldurursun. Sistem otomatik güvenlik kontrolleri yapar ve vakaların büyük çoğunluğunda dakikalar içinde bir onay verir. Bu onay elektronik olarak pasaportuna bağlanır. Yazdırılacak ya da pasaportuna yapıştırılacak bir şey yoktur.`,
  "5365230f": `<strong>ETIAS bir vize değildir.</strong> Yeni bir giriş hakkı vermez; <em>zaten</em> vizeden muaf olan yolcuların ön taramasıdır. Nihai kararı yine sınır görevlileri verir ve üstüne 180 günde 90 gün sınırı da uygulanmaya devam eder.`,
  "f0f3f932": `Kimler için gerekli`,
  "de88b910": `ETIAS, şu anda Schengen Bölgesi'nde kısa kalışlar için vizesiz olan ülkelerin vatandaşları için geçerlidir: örneğin Amerika Birleşik Devletleri, Birleşik Krallık, Kanada, Avustralya, Brezilya, Japonya ve düzinelerce diğer ülkeden gelen yolcular. Pasaportun zaten Schengen vizesi gerektiriyorsa hiçbir şey değişmez: vizeye başvurmaya devam edersin ve ETIAS sana uygulanmaz. Pasaportun bugün vizesizse, ETIAS eklenen yeni adımdır.`,
  "9a2687aa": `Kimler muaf`,
  "d56822c0": `AB ve Schengen ülkelerinin vatandaşları.`,
  "bf277adc": `Schengen oturma izni ya da uzun süreli ulusal vize sahipleri.`,
  "68b9e0af": `Kısa süreli Schengen vizesi olanlar (zaten vize sürecinde taranmış oluyorlar).`,
  "1b13607e": `Maliyet, geçerlilik ve zamanlama`,
  "83a4a679": `ETIAS ucuz ve uzun ömürlü olacak şekilde tasarlandı: küçük, tek seferlik bir ücret (18 yaş altı ve 70 yaş üstü ücretten muaf), birkaç yıl ya da pasaportun sona erene kadar, hangisi önce gelirse, geçerli. Bu geçerlilik süresi içinde birden fazla seyahat için kullanabilirsin. Onayların çoğu anlık olsa da bazıları günler sürebilen manuel incelemeye gönderildiğinden, tavsiye uçuştan önceki gece değil, rezervasyondan çok önce başvurmaktır.`,
  "d74dfca5": `Dolandırıcılıktan nasıl kaçınılır`,
  "8e7f2593": `Yeni bir seyahat izni sistemi devreye girdiğinde, şişirilmiş “hizmet” ücretleri alan benzer görünümlü siteler ortaya çıkar. Yalnızca resmî AB ETIAS portalı üzerinden başvur. Resmî ücretin kat kat fazlasını isteyen ya da sistem resmen yayına girmeden ödeme isteyen her siteye şüpheyle yaklaşılmalıdır.`,
  "33b3d8f4": `ETIAS, ETA, ESTA: hangisi hangisi`,
  "f787ead1": `Bunların hepsi aynı ailedendir: vizesiz yolcular için elektronik izinler. ESTA Amerika Birleşik Devletleri'nin, eTA Kanada'nın sürümüdür; Birleşik Krallık kendi ETA'sını başlattı, ETIAS ise Avrupa'nındır. Hepsi aynı şekilde çalışır: çevrimiçi kayıt ol, pasaportuna bağlı bir onay al, uçağına bin, ama her biri ayrıdır ve yalnızca kendi bölgesinde geçerlidir. Bu kategorinin diğerlerine nasıl oturduğunu görmek için <a href="/guides/visa-types-explained/">vize türleri rehberimize</a> bak.`,
  "1cbd353e": `ETIAS şu anda yürürlükte mi?`,
  "fed43c8c": `Başlangıcı birkaç kez planlandı ve ertelendi. Güncel başlangıç tarihi için resmî AB takvimine bak ve uyruğunun kapsamda olup olmadığını doğrulamak için <a href="/etias/">ETIAS kontrolümüzü</a> kullan.`,
  "fc3afb6d": `ETIAS, Schengen vizesinin yerini alıyor mu?`,
  "3daffd31": `Hayır. Yalnızca zaten vizesiz olan kişiler için geçerlidir. Vize gerektiren uyruklar normal vizeyi kullanmaya devam eder.`,
  "6c3210af": `ETIAS ile ne kadar kalabilirim?`,
  "1a679141": `Hakkını değiştirmez: herhangi bir 180 günlük dönemde 90 gün kuralı aynen geçerlidir. <a href="/guides/schengen-90-180-rule/">90/180 rehberine</a> bak.`,
  "47f168d9": `Kendi pasaportun için kontrol et`,
  "0ee459ad": `<a href="/etias/">ETIAS kontrolü</a>: 2026 izni uyruğun için gerekli mi?`,
  "c3eea2fd": `<a href="/schengen-calculator/">Schengen 90/180 hesaplayıcı</a>: izin verilen günlerini takip et.`,
  "8b62c32a": `<a href="/">Etkileşimli küre</a>: her Avrupa ülkesi için vize durumunu gör.`,
};
