// Turkish text for /privacy/ in the formal register usual for legal text. See scripts/tr-strings/index.js.
module.exports = {
  "47b37efc": `Son güncelleme: 24 Eylül 2026`,
  "e4f8a872": `travelnow.info ücretsiz bir vize ve seyahat başvuru kaynağıdır. Bu politika, web sitesinin ve mobil uygulamanın hangi kişisel verileri hangi amaçla işlediğini ve bunları nasıl kontrol edebileceğinizi açıklar. Tüm araçlar hesap olmadan çalışır ve hesabınız yoksa hakkınızda hiçbir kişisel veri saklamayız.`,
  "27fd5670": `1. Veri sorumlusu`,
  "ac7c998d": `Veri sorumlusu, travelnow.info'yu işleten Uygar Atalay'dır. Verilerinizle ilgili her konuda <a href="mailto:hello@travelnow.info">hello@travelnow.info</a> adresine yazabilirsiniz. Başvurulara 30 gün içinde yanıt veririz.`,
  "73a9e32e": `2. Siteyi hesapsız kullanırken`,
  "c0f1f100": `<strong>Seçimleriniz cihazınızda kalır.</strong> Seçtiğiniz pasaport, izlediğiniz ülkeler, planladığınız seyahat ve ayarlarınız tarayıcınızın yerel depolamasında tutulur. Bu bilgiler bize ulaşmaz.`,
  "285a8595": `<strong>Saat dilimi.</strong> İlk ziyaretinizde site, size bir pasaport önerebilmek için cihazınızın saat dilimini okur. Bu işlem tarayıcınızda gerçekleşir ve bize hiçbir şey gönderilmez.`,
  "045c5588": `<strong>Barındırma.</strong> Siteyi Cloudflare sunar ve korur. Bunun için IP adresiniz, tarayıcı türünüz ve istenen sayfa gibi teknik istek verilerini işler.`,
  "346e56d5": `<strong>İstatistikler.</strong> Ziyaretleri çerez kullanmayan Cloudflare Web Analytics ve Google Analytics 4 ile sayarız. AB ve AEA ülkelerinde, Birleşik Krallık'ta, İsviçre'de ve Türkiye'de Google Analytics çerezsiz çalışır ve cihazınızda hiçbir şey saklamaz. Diğer ülkelerde birinci taraf <code>_ga</code> ve <code>_ga_*</code> çerezlerini kullanabilir. Google Analytics 4, IP adreslerini kaydetmez ve saklamaz.`,
  "93df92d5": `3. Hesap oluşturursanız`,
  "11970f98": `Hesap, kaydettiğiniz öğeleri tüm cihazlarınızda kullanmanızı sağlar. Giriş yaptığınız e-posta adresini veya telefon numarasını ve kaydetmeyi seçtiğiniz öğeleri saklarız: pasaport ve pasaport türü, oturum izinleri, izlenen ülkeler, planlanan seyahat, Schengen hesaplayıcı kayıtları, dil ve tema. Pasaport numarası, belge veya ödeme bilgisi asla istemeyiz.`,
  "09c71e98": `Google ile, e-posta adresi ve şifreyle ya da telefon numarası ve SMS ile gönderilen tek kullanımlık kodla giriş yapabilirsiniz. Hesaplar Google Firebase (Authentication ve Cloud Firestore) üzerinde çalışır. Kaydedilen öğeler Google'ın Avrupa Birliği bölgesinde saklanır ve erişim kuralları bunları yalnızca sizin okuyup değiştirmenize izin verir.`,
  "9b39adcd": `<a href="/account/">Hesap sayfasında</a> verilerinizi indirebilir veya hesabınızı içindeki her şeyle birlikte silebilirsiniz. Silme işlemi hemen gerçekleşir. Bu verileri, talep ettiğiniz hizmeti sunmak için işleriz (GDPR madde 6(1)(b); KVKK madde 5/2-c).`,
  "f21d2824": `4. Bildirimler`,
  "42959f3d": `Bildirimler, siz tarayıcınızda veya uygulamada açana kadar kapalıdır. Açtığınızda, mesajın doğru cihaza uygun bir saatte ulaşması için o cihazın bildirim anahtarını, platformunu (web, iOS veya Android), arayüz dilinizi ve saat diliminizi saklarız. Yalnızca pasaportunuz veya izlediğiniz bir ülke için vize kuralı değiştiğinde ya da seyahatinizdeki bir ülke için resmi güvenlik uyarısı değiştiğinde bildirim göndeririz. Asla pazarlama mesajı göndermeyiz. Bildirimleri kapattığınızda, çıkış yaptığınızda veya hesabınızı sildiğinizde anahtar silinir. Hukuki dayanak açık rızanızdır (GDPR madde 6(1)(a); KVKK madde 5/1) ve rızanızı istediğiniz zaman geri alabilirsiniz.`,
  "c85fcc51": `5. Reklamlar`,
  "f3d1611f": `Web sitesi Google AdSense, uygulama ise Google AdMob kullanır. Reklam gösterildiğinde Google ve iş ortakları, reklamları göstermek ve ölçmek için çerezler veya cihazınızın reklam kimliğini kullanabilir; buna bu ve diğer sitelerdeki önceki ziyaretlerinize dayalı reklamlar da dahildir. AB ve AEA ülkelerinde, Birleşik Krallık'ta ve İsviçre'de kişiselleştirilmiş reklamlar yalnızca Google'ın onay mesajında kabul ettikten sonra gösterilir. iOS'ta uygulama herhangi bir izlemeden önce izninizi ister ve hayır demeniz başka hiçbir şeyi değiştirmez. Kişiselleştirilmiş reklamları <a href="https://adssettings.google.com" target="_blank" rel="noopener">Google reklam ayarlarından</a> kapatabilir, <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener">Google'ın hizmetlerini kullanan sitelerden gelen bilgileri nasıl kullandığını</a> okuyabilirsiniz.`,
  "61a0161a": `6. Hizmet sağlayıcılar`,
  "567d3200": `İki hizmet sağlayıcıyla çalışırız; her biri kendi gizlilik koşullarına ve yasanın gerektirdiği yerlerde veri işleme sözleşmelerine tabidir:`,
  "c0c114b7": `<strong>Cloudflare, Inc.</strong>: barındırma, içerik dağıtımı, güvenlik ve web analitiği.`,
  "65e9dcbd": `<strong>Google</strong> (Google Ireland Ltd ve Google LLC): giriş, hesap depolama ve bildirimler için Firebase, Google Analytics, AdSense ve AdMob.`,
  "b4676e0d": `Kişisel verileri satmayız ve yasa gerektirmedikçe başka hiç kimseyle paylaşmayız. Büyükelçilikler, resmi başvuru portalları veya Buy Me a Coffee sayfamız gibi diğer sitelere verilen bağlantılar, kendi gizlilik politikaları olan hizmetlere gider.`,
  "3d0ec881": `7. Yurt dışına aktarım`,
  "3008f3f0": `Google ve Cloudflare verileri Amerika Birleşik Devletleri'nde ve başka ülkelerde işleyebilir. Veriler AB ve AEA, Birleşik Krallık veya Türkiye dışına çıktığında bu şirketler, Avrupa Komisyonu'nun Standart Sözleşme Maddeleri veya AB-ABD Veri Gizliliği Çerçevesi gibi yasal olarak tanınan güvencelere dayanır. Türkiye'den yapılan aktarımlar için KVKK madde 9'daki güvenceler uygulanır.`,
  "8ae863e3": `8. Saklama süreleri`,
  "0292e9ae": `Hesap verileri: hesabınızı silene kadar.`,
  "71136269": `Bildirim anahtarları: bildirimleri kapatana, çıkış yapana veya hesabınızı silene kadar ya da anahtar çalışmaz hale gelene kadar.`,
  "76d54d1e": `Google Analytics verileri: en fazla 14 ay.`,
  "84d88590": `Bize gönderdiğiniz e-postalar: yanıt vermek ve takip etmek için gerektiği sürece.`,
  "3e536d6e": `9. Haklarınız`,
  "68a125e9": `Bulunduğunuz yere bağlı olarak, GDPR, Birleşik Krallık GDPR'ı ve 6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) kapsamında, verilerinize erişmeyi, bunları düzeltmeyi veya silmeyi, bir kopyasını almayı, kullanımını kısıtlamayı veya itiraz etmeyi ve rızanızı istediğiniz zaman geri almayı talep edebilirsiniz. Bunların çoğunu hesap sayfasında kendiniz yapabilirsiniz. Diğer talepleriniz için <a href="mailto:hello@travelnow.info">hello@travelnow.info</a> adresine yazın. Ayrıca veri koruma otoritenize şikâyette bulunabilirsiniz; Türkiye'de bu kurum Kişisel Verileri Koruma Kurumu'dur (KVKK). Kaliforniya'da yaşıyorsanız kişisel bilgileriniz hakkında bilgi alma ve bunları sildirme hakkınız vardır ve bu haklarınızı kullandığınız için size farklı davranmayız.`,
  "89ec1ec4": `10. Çocuklar`,
  "aac037b5": `travelnow.info 16 yaşından küçük çocuklara yönelik değildir ve onların kişisel verilerini bilerek toplamayız. Bir çocuğun hesap oluşturduğunu düşünüyorsanız bize yazın, hesabı sileriz.`,
  "785deadd": `11. Güvenlik`,
  "aa78eede": `Tüm bağlantılar HTTPS kullanır, her hesap kaydını yalnızca sahibi okuyup değiştirebilir ve yalnızca hizmetin ihtiyaç duyduğu verileri toplarız. Hiçbir sistem tamamen güvenli değildir; bu nedenle mutlak güvenlik garanti edemeyiz.`,
  "a72a0c21": `12. Değişiklikler`,
  "50138e9e": `Hizmet veya mevzuat değiştiğinde bu politikayı güncelleriz; sayfanın başındaki tarih geçerli sürümü gösterir. Bir değişiklik daha önce verdiğiniz verileri etkiliyorsa bunu sitede ve uygulamada belirtiriz.`,
  "e7ff55ec": `<a href="/terms/">Kullanım Koşulları</a> sayfasına da bakabilirsiniz.`,
};
