// Re-stamps the shared <head> assets, masthead and footer into every
// hand-written static page, from scripts/partials.js (+ assets/site-nav.js).
//
// Run after changing the nav, footer or asset version:
//   node scripts/apply-chrome.js
//
// Each page carries three marker pairs; everything between them is replaced:
//   <!-- chrome:head -->     … <!-- /chrome:head -->
//   <!-- chrome:masthead --> … <!-- /chrome:masthead -->
//   <!-- chrome:footer -->   … <!-- /chrome:footer -->
// Passport pages are generated by scripts/generate-seo.js, which uses the same
// partials directly, so they are not touched here.

const fs = require("fs");
const path = require("path");
const { headAssets, masthead, footer } = require("./partials");

const ROOT = path.resolve(__dirname, "..");

// URL path for aria-current + whether the page loads data/static-i18n.js.
function pagesToStamp() {
  const out = [];
  const walk = (dir) => {
    for (const name of fs.readdirSync(dir)) {
      const full = path.join(dir, name);
      const rel = path.relative(ROOT, full).replace(/\\/g, "/");
      if (fs.statSync(full).isDirectory()) {
        if (/^(node_modules|backend|passport|\.git|\.github|\.claude|functions|scripts|data|assets|components|screenshots)$/.test(rel)) continue;
        walk(full);
      } else if (name === "index.html" || rel === "404.html") {
        out.push(rel);
      }
    }
  };
  walk(ROOT);
  return out;
}

function replaceBetween(html, name, content) {
  const re = new RegExp(`<!-- chrome:${name} -->[\\s\\S]*?<!-- /chrome:${name} -->`);
  if (!re.test(html)) return null;
  return html.replace(re, `<!-- chrome:${name} -->\n${content}\n<!-- /chrome:${name} -->`);
}

let stamped = 0;
for (const rel of pagesToStamp()) {
  const file = path.join(ROOT, rel);
  const raw = fs.readFileSync(file, "utf8");
  const eol = raw.includes("\r\n") ? "\r\n" : "\n";
  let html = raw.replace(/\r\n/g, "\n");
  if (!html.includes("<!-- chrome:masthead -->")) continue; // SPA shells, unstamped pages

  const urlPath = rel === "404.html" ? "/404" : "/" + rel.replace(/index\.html$/, "");
  const i18n = html.includes("static-i18n.js");
  for (const [name, content] of [
    ["head", headAssets()],
    ["masthead", masthead({ path: urlPath, i18n })],
    ["footer", footer()],
  ]) {
    const next = replaceBetween(html, name, content);
    if (next == null) throw new Error(`${rel}: missing chrome:${name} markers`);
    html = next;
  }
  fs.writeFileSync(file, html.replace(/\n/g, eol));
  stamped++;
}
console.log(`✓ stamped chrome into ${stamped} static pages`);
