#!/usr/bin/env node
// Builds the Turkish twins of the hand-written pages: /tr/<path>/index.html.
//
//   node scripts/build-tr.js            write the twins (fails if a page is not fully Turkish)
//   node scripts/build-tr.js --check    write nothing; exit 1 if a twin is stale or incomplete
//   node scripts/build-tr.js --todo     list the English text still to translate, per page
//   node scripts/build-tr.js --todo guides    … for one page
//
// Why real pages and not the client-side translation the site already has:
// crawlers don't run JS, so a translated overlay is invisible to them. A twin at
// /tr/… carries the Turkish text in the HTML, <html lang="tr">, a Turkish
// <title>/description, and hreflang links both ways, so Turkish searchers get the
// Turkish page. The passport pages are generated by scripts/generate-seo.js; the
// visa map (/) is assembled here from index.html (the SPA shell).
//
// Where the Turkish text comes from, in order:
//   1. scripts/tr-strings/*.js — one entry per translatable unit of the page,
//      keyed by a hash of its English source (a paragraph with its inline markup,
//      a bare text node, or an attribute). Written for long-form prose, where a
//      sentence spans <a>/<strong> and word-for-word replacement would be wrong.
//      If the English changes, its hash changes and the page fails the build
//      until the translation is updated — a twin can't silently go stale.
//   2. data/static-i18n.js — the dictionary the browser uses for short UI
//      strings, run over whatever step 1 left (in jsdom, so it is the same code).
// Anything still English after both fails the build: better no Turkish page than
// a half-English one under lang="tr".
//
// Order of work when a page changes:
//   node scripts/apply-chrome.js   (re-stamps masthead/footer/head)
//   node scripts/build-tr.js
//   node scripts/generate-seo.js   (the sitemap lists the twins)

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..");
const { JSDOM } = require(path.join(ROOT, "tools", "node_modules", "jsdom"));
const { SITE_URL, TR_PAGES, hasTr, toTr } = require("./locales");
const { headAssets, masthead, footer, langHead } = require("./partials");
const META = require("./tr-meta");
const STRINGS = require("./tr-strings");

const args = process.argv.slice(2);
const CHECK = args.includes("--check");
const TODO = args.includes("--todo");
// A page to limit --todo/--check to: "about", "guides/schengen-90-180-rule", "/about/"
// (write it without the leading slash in Git Bash, which rewrites /paths).
const only = args.find((a) => !a.startsWith("--"));
const ONLY = only ? "/" + only.replace(/^\/+|\/+$/g, "") + "/" : null;
const STATIC_I18N = fs.readFileSync(path.join(ROOT, "data", "static-i18n.js"), "utf8");

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), "utf8").replace(/\r\n/g, "\n");
const pageFile = (p) => (p === "/" ? "index.html" : p.slice(1) + "index.html");
const norm = (s) => String(s).replace(/\s+/g, " ").trim();
const hash = (kind, s) => crypto.createHash("sha1").update(kind + ":" + norm(s)).digest("hex").slice(0, 8);
const wordsOf = (s) => (s.match(/[A-Za-z][A-Za-z'’-]{2,}/g) || []);
const hasLetters = (s) => /[A-Za-z]{2}/.test(s);

function replaceBetween(html, name, content) {
  const re = new RegExp(`<!-- chrome:${name} -->[\\s\\S]*?<!-- /chrome:${name} -->`);
  if (!re.test(html)) return null;
  return html.replace(re, () => `<!-- chrome:${name} -->\n${content}\n<!-- /chrome:${name} -->`);
}

function setMeta(html, attr, key, value) {
  const re = new RegExp(`(<meta ${attr}="${key}" content=")[^"]*(")`);
  if (!re.test(html)) return html;
  return html.replace(re, (_, a, b) => a + esc(value) + b);
}

// English page → Turkish head: <html lang>, title, description, canonical, og:*.
function localiseHead(html, enPath, meta) {
  const url = SITE_URL + toTr(enPath);
  html = html.replace(/<html lang="en"[^>]*>/, '<html lang="tr" data-page-lang="tr">');
  html = html.replace(/<title>[^<]*<\/title>/, () => `<title>${esc(meta.title)}</title>`);
  html = setMeta(html, "name", "description", meta.description);
  html = html.replace(/(<link rel="canonical" href=")[^"]*(")/, (_, a, b) => a + url + b);
  html = setMeta(html, "property", "og:title", meta.ogTitle || meta.title);
  html = setMeta(html, "property", "og:description", meta.ogDescription || meta.description);
  html = setMeta(html, "property", "og:url", url);
  html = setMeta(html, "name", "twitter:title", meta.ogTitle || meta.title);
  html = setMeta(html, "name", "twitter:description", meta.ogDescription || meta.description);
  if (!/property="og:locale"/.test(html)) {
    html = html.replace(/(<meta property="og:url"[^>]*>)/, '$1\n<meta property="og:locale" content="tr_TR">');
  }
  return html;
}

// ── Translatable units ─────────────────────────────────────────────────────────
const INLINE = new Set("a abbr b bdi bdo br cite code data dfn em i kbd mark q s samp small span strong sub sup time u var wbr".split(" "));
const SKIP = new Set(["script", "style", "noscript", "svg", "template", "textarea"]);
const ATTRS = ["placeholder", "title", "aria-label", "alt"];

const skipped = (el) =>
  SKIP.has(el.localName) || el.hasAttribute("data-no-i18n") ||
  el.matches("header.masthead, footer.site-foot, .doc-band");
const inlineOnly = (el) => [...el.children].every((c) => INLINE.has(c.localName) && inlineOnly(c));

// A unit is the largest stretch of text that has to be translated as a whole: an
// element whose children are all inline (a paragraph with its <a>/<strong>), or a
// bare text node next to block children. Plus attribute values.
function collectUnits(doc) {
  const units = [];
  const walk = (el) => {
    if (skipped(el)) return;
    if (el !== doc.body && inlineOnly(el) && hasLetters(el.textContent)) {
      units.push({ kind: "html", el, key: norm(el.innerHTML) });
      return;
    }
    for (const n of el.childNodes) {
      if (n.nodeType === 3) { if (hasLetters(n.nodeValue)) units.push({ kind: "text", node: n, key: norm(n.nodeValue) }); }
      else if (n.nodeType === 1) walk(n);
    }
  };
  walk(doc.body);
  doc.querySelectorAll("*").forEach((el) => {
    if (skipped(el) || el.closest("header.masthead, footer.site-foot, [data-no-i18n], svg")) return;
    for (const a of ATTRS) {
      const v = el.getAttribute(a);
      if (v && hasLetters(v)) units.push({ kind: "attr", el, attr: a, key: a + "=" + norm(v) });
    }
  });
  for (const u of units) u.id = hash(u.kind, u.key);
  return units;
}

// Step 1: apply tr-strings entries. Returns the units that were handled.
function applyStrings(units) {
  const done = new Set();
  for (const u of units) {
    const tr = STRINGS[u.id];
    if (tr === undefined) continue;
    done.add(u);
    if (tr === true) continue; // keep as is (proper noun, code…)
    if (u.kind === "html") u.el.innerHTML = tr;
    else if (u.kind === "text") {
      const raw = u.node.nodeValue, t = raw.trim();
      u.node.nodeValue = raw.slice(0, raw.indexOf(t)) + tr + raw.slice(raw.indexOf(t) + t.length);
    } else u.el.setAttribute(u.attr, tr);
  }
  return done;
}

// Text nodes under an element (or the node itself), for the leftover check.
function textNodesOf(u) {
  if (u.kind === "text") return [u.node];
  if (u.kind === "attr") return [];
  const out = [], w = u.el.ownerDocument.createTreeWalker(u.el, 4);
  while (w.nextNode()) out.push(w.currentNode);
  return out;
}

async function translate(html, enPath) {
  const dom = new JSDOM(html, { url: SITE_URL + toTr(enPath), runScripts: "outside-only" });
  const { window } = dom;
  const doc = window.document;
  if (doc.readyState !== "complete") await new Promise((r) => window.addEventListener("load", r));

  const units = collectUnits(doc);
  const before = new Map();
  for (const u of units) {
    if (u.kind === "attr") before.set(u, u.el.getAttribute(u.attr));
    else for (const n of textNodesOf(u)) before.set(n, n.nodeValue);
  }
  const handled = applyStrings(units);

  // Step 2: the browser dictionary over what is left. The observer that
  // re-translates later DOM changes would only fire after the window is closed.
  delete window.MutationObserver;
  window.eval(STATIC_I18N);

  const left = [];
  for (const u of units) {
    if (handled.has(u)) continue;
    let english = false;
    if (u.kind === "attr") english = u.el.getAttribute(u.attr) === before.get(u) && wordsOf(before.get(u)).length > 0;
    else english = textNodesOf(u).some((n) => before.has(n) && n.nodeValue === before.get(n) && wordsOf(n.nodeValue).length > 0);
    if (english) left.push(u);
  }
  return { dom, left, total: units.length };
}

// Internal links go to the Turkish twin when there is one.
function rewriteLinks(doc) {
  doc.querySelectorAll("a[href]").forEach((a) => {
    const h = a.getAttribute("href");
    if (!h.startsWith("/") || h.startsWith("//")) return;
    const m = h.match(/^([^?#]*)(.*)$/);
    if (hasTr(m[1])) a.setAttribute("href", toTr(m[1]) + m[2]);
  });
}

// JSON-LD: point at the twin, say it's Turkish, use the Turkish headline/description.
function rewriteJsonLd(doc, enPath, meta) {
  const url = SITE_URL + toTr(enPath);
  const h1 = doc.querySelector("h1");
  const h1Text = h1 ? norm(h1.textContent) : null;
  doc.querySelectorAll('script[type="application/ld+json"]').forEach((s) => {
    let j;
    try { j = JSON.parse(s.textContent); } catch (e) { return; }
    const walk = (o) => {
      for (const k of Object.keys(o)) {
        const v = o[k];
        if (v && typeof v === "object") { walk(v); continue; }
        if ((k === "url" || k === "mainEntityOfPage" || k === "item") && typeof v === "string" && v.startsWith(SITE_URL)) {
          const p = v.slice(SITE_URL.length) || "/";
          if (hasTr(p)) o[k] = SITE_URL + toTr(p);
        }
      }
    };
    walk(j);
    if (j["@type"] === "Article") j.headline = meta.h1 || h1Text || j.headline;
    if (j["@type"] === "WebApplication") { j.name = meta.h1 || h1Text || j.name; if (j.url === undefined) j.url = url; }
    if (j.description) j.description = meta.description;
    j.inLanguage = "tr";
    s.textContent = "\n" + JSON.stringify(j, null, 2) + "\n";
  });
}

async function buildPage(enPath) {
  const meta = META[enPath];
  if (!meta) throw new Error(`tr-meta.js has no entry for ${enPath}`);
  const file = pageFile(enPath);
  let html = read(file);
  if (!html.includes("<!-- chrome:masthead -->")) throw new Error(`${file}: no chrome markers`);
  const i18n = html.includes("static-i18n.js");
  for (const [name, content] of [
    ["head", headAssets({ enPath, lang: "tr" })],
    ["masthead", masthead({ path: enPath, i18n, lang: "tr" })],
    ["footer", footer({ lang: "tr" })],
  ]) html = replaceBetween(html, name, content);
  html = localiseHead(html, enPath, meta);

  const { dom, left, total } = await translate(html, enPath);
  const doc = dom.window.document;
  rewriteLinks(doc);
  rewriteJsonLd(doc, enPath, meta);
  doc.querySelectorAll("*").forEach((el) => {
    for (const a of [...el.attributes]) if (a.name.startsWith("data-orig-")) el.removeAttribute(a.name);
  });
  doc.documentElement.setAttribute("lang", "tr");
  doc.documentElement.setAttribute("dir", "ltr");
  const out = "<!DOCTYPE html>\n" + doc.documentElement.outerHTML + "\n";
  dom.window.close();
  return { out, left, total };
}

// ── The visa map (/tr/): the SPA shell with a Turkish crawlable fallback ────────
const HOME_FALLBACK_TR = require("./tr-home-fallback");

function buildHome() {
  const meta = META["/"];
  let html = read("index.html");
  html = localiseHead(html, "/", meta);
  // hreflang + language routing live in a stamped block (apply-chrome.js).
  html = html.replace(/<!-- lang:head -->[\s\S]*?<!-- \/lang:head -->/, () => `<!-- lang:head -->\n${langHead({ enPath: "/", lang: "tr" })}\n<!-- /lang:head -->`);
  // The shell lives one directory deeper: relative script paths must be absolute.
  html = html.replace(/(<script src=")(?!\/|https?:)/g, "$1/");
  const fb = /<main class="seo-fallback">[\s\S]*?<\/main>/;
  const en = html.match(fb);
  if (!en) throw new Error("index.html: no seo-fallback block");
  // The Turkish block is hand-written; make sure it still links to the same places.
  const hrefs = (h) => [...h.matchAll(/href="([^"]+)"/g)].map((m) => m[1]);
  const want = hrefs(en[0]).map((h) => (hasTr(h) ? toTr(h) : h)).sort().join("\n");
  const got = hrefs(HOME_FALLBACK_TR).sort().join("\n");
  if (want !== got) throw new Error("scripts/tr-home-fallback.js links differ from the English seo-fallback in index.html:\n" + want + "\n---\n" + got);
  return html.replace(fb, () => HOME_FALLBACK_TR);
}

async function main() {
  const jobs = [];
  let bad = 0;
  for (const p of TR_PAGES) {
    if (p === "/passport/") continue; // generate-seo.js writes the directory + every /passport/<iso>/
    if (ONLY && ONLY !== p) continue;
    if (p === "/") { jobs.push({ p, out: buildHome(), left: [], total: 0 }); continue; }
    jobs.push({ p, ...(await buildPage(p)) });
  }

  const seen = new Set();
  for (const j of jobs) {
    const words = j.left.reduce((n, u) => n + wordsOf(u.kind === "attr" ? u.key : u.kind === "html" ? u.el.textContent : u.node.nodeValue).length, 0);
    if (j.left.length) bad++;
    if (TODO) {
      console.log(`\n## ${j.p}  — ${j.left.length} unit(s), ~${words} words to translate`);
      for (const u of j.left) {
        if (seen.has(u.id)) continue;
        seen.add(u.id);
        console.log(`[${u.id}] ${u.kind === "attr" ? `(${u.key})` : u.kind === "text" ? u.key : `<${u.el.localName}> ${u.key}`}`);
      }
    } else {
      console.log(`${j.left.length ? "✗" : "✓"} ${j.p.padEnd(44)} ${String(j.total - j.left.length).padStart(4)}/${String(j.total).padEnd(4)} units in Turkish${j.left.length ? `, ${j.left.length} still English (${words} words)` : ""}`);
    }
  }
  if (TODO) return;

  if (bad) {
    console.error(`\n${bad} page(s) not fully translated — run with --todo to list what is missing. Nothing written.`);
    process.exit(1);
  }
  if (CHECK) {
    let stale = 0;
    for (const j of jobs) {
      const f = path.join(ROOT, toTr(j.p).slice(1), "index.html");
      const cur = fs.existsSync(f) ? fs.readFileSync(f, "utf8").replace(/\r\n/g, "\n") : "";
      if (cur !== j.out) { stale++; console.log(`stale: ${toTr(j.p)}`); }
    }
    process.exit(stale ? 1 : 0);
  }
  for (const j of jobs) {
    const dir = path.join(ROOT, toTr(j.p).slice(1));
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "index.html"), j.out);
  }
  console.log(`\n✓ wrote ${jobs.length} Turkish twins`);
}

main().catch((e) => { console.error(e); process.exit(1); });
