// One-off: copy the Google Fonts the site uses into /assets/fonts and write /assets/fonts.css,
// so visitors' browsers never contact Google for fonts (GDPR: a German court fined a site for
// the IP transfer). Re-run only when the font list changes. Fonts are SIL OFL licensed.
// Usage: node tools/selfhost-fonts.js
const fs = require("fs");
const path = require("path");
const https = require("https");

const CSS_URL = "https://fonts.googleapis.com/css2?family=Sofia+Sans:ital,wght@0,400..700;1,400..600&family=Sofia+Sans+Extra+Condensed:wght@600..850&family=DM+Mono:wght@400;500&family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&display=swap";
const KEEP = new Set(["latin", "latin-ext", "arabic"]);
const OUT = path.join(__dirname, "..", "assets", "fonts");
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { "User-Agent": UA } }, (res) => {
      if (res.statusCode !== 200) return reject(new Error(res.statusCode + " " + url));
      const chunks = []; res.on("data", (c) => chunks.push(c)); res.on("end", () => resolve(Buffer.concat(chunks)));
    }).on("error", reject);
  });
}

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  const css = (await get(CSS_URL)).toString("utf8");
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  let out = "/* Self-hosted copies of the Google Fonts the site uses (SIL OFL). Generated by tools/selfhost-fonts.js. */\n";
  const done = new Map();
  let bytes = 0, n = 0;
  for (const [, subset, face] of blocks) {
    if (!KEEP.has(subset)) continue;
    const url = face.match(/url\((https:[^)]+\.woff2)\)/)[1];
    const family = face.match(/font-family:\s*'([^']+)'/)[1];
    const style = face.match(/font-style:\s*(\w+)/)[1];
    const weight = face.match(/font-weight:\s*([\d ]+)/)[1].trim().replace(/ /g, "-");
    const name = family.toLowerCase().replace(/\s+/g, "-") + "-" + style + "-" + weight + "-" + subset + ".woff2";
    if (!done.has(url)) {
      const buf = await get(url);
      fs.writeFileSync(path.join(OUT, name), buf);
      bytes += buf.length; n++;
      done.set(url, name);
    }
    out += face.replace(url, "/assets/fonts/" + done.get(url)).replace(/\n\s*/g, " ") + "\n";
  }
  fs.writeFileSync(path.join(__dirname, "..", "assets", "fonts.css"), out);
  console.log("fonts: " + n + " files, " + Math.round(bytes / 1024) + " KB; css faces: " + (out.split("@font-face").length - 1));
})().catch((e) => { console.error(e.message); process.exit(1); });
